//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milcom
{
    using System;
    using System.Collections.Generic;
    
    public partial class certifikat
    {
        public int id { get; set; }
        public string datum_izdavanja { get; set; }
        public int rezultat_id { get; set; }
    
        public virtual rezultat rezultat { get; set; }
    }
}
