//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milcom
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilcomEntities : DbContext
    {
        public MilcomEntities()
            : base("name=MilcomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<certifikat> certifikat { get; set; }
        public DbSet<korisnik> korisnik { get; set; }
        public DbSet<odgovor> odgovor { get; set; }
        public DbSet<pitanje> pitanje { get; set; }
        public DbSet<polaznik> polaznik { get; set; }
        public DbSet<rezultat> rezultat { get; set; }
        public DbSet<test> test { get; set; }
        public DbSet<tip_korisnik> tip_korisnik { get; set; }
        public DbSet<tip_polaganja> tip_polaganja { get; set; }
    }
}
