//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milcom
{
    using System;
    using System.Collections.Generic;
    
    public partial class pitanje
    {
        public pitanje()
        {
            this.odgovor = new HashSet<odgovor>();
            this.test = new HashSet<test>();
        }
    
        public int id { get; set; }
        public string tekst { get; set; }
        public int tip_polaganja_id { get; set; }
    
        public virtual ICollection<odgovor> odgovor { get; set; }
        public virtual tip_polaganja tip_polaganja { get; set; }
        public virtual ICollection<test> test { get; set; }
    }
}
