//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milcom
{
    using System;
    using System.Collections.Generic;
    
    public partial class polaznik
    {
        public polaznik()
        {
            this.korisnik = new HashSet<korisnik>();
            this.rezultat = new HashSet<rezultat>();
        }
    
        public int oib { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public System.DateTime datum_rodjenja { get; set; }
        public string adresa { get; set; }
        public string telefon { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<korisnik> korisnik { get; set; }
        public virtual ICollection<rezultat> rezultat { get; set; }
    }
}
