//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Milcom
{
    using System;
    using System.Collections.Generic;
    
    public partial class rezultat
    {
        public rezultat()
        {
            this.certifikat = new HashSet<certifikat>();
            this.test = new HashSet<test>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> datum_polaganja { get; set; }
        public Nullable<int> pokusaj { get; set; }
        public Nullable<int> bodovi { get; set; }
        public int tip_polaganja_id { get; set; }
        public int polaznik_oib { get; set; }
    
        public virtual ICollection<certifikat> certifikat { get; set; }
        public virtual polaznik polaznik { get; set; }
        public virtual ICollection<test> test { get; set; }
        public virtual tip_polaganja tip_polaganja { get; set; }
    }
}
